### ISSUE TITLE
About the post-install-cmd example and installing with --no-dev

### ISSUE THREAD

**Issue by devnix** [BrainMaestro/composer-git-hooks#100] opened 2019-10-14 15:02 UTC
Hi! I found this package extra useful for my workflow at my job. I just wanted to share my experience implementing it and a couple of thoughts.

I felt the `"post-install-cmd": "cghooks add --ignore-lock",` suggestion very misleading, if I understood correctly, it would add the `cghooks.lock` file to my gitignore (in my case breaking my gitignore, as the last line was not empty), and my coworker would get the gitignore modified too (as the package would not find a `cghooks.lock` file.

On the other hand, I had issues when doing a `composer install --no-dev` deploy.

My first attemp was checking the `COMPOSER_DEV_MODE` env variable, but it did not work in my Docker environment. I solved it with a `command -v` call. Also, I had to specify the `git-dir` because the package was not finding it on my Docker container (and I don't have any clue about why).

My last problem appeared when doing `composer install` after a `composer install --no-dev`. I had to solve this by uninstalling the hooks before every installation.

This is an excerpt of my final `composer.json` file. I think that the readme could be improved, and the workflow rethinked to be easier!

```json
{
	"require-dev": {
		"overtrue/phplint": "^1.1",
		"brainmaestro/composer-git-hooks": "^2.8"
	},
	"scripts": {
		"pre-install-cmd": "command -v vendor/bin/cghooks >/dev/null 2>&1 || exit 0; vendor/bin/cghooks remove --git-dir=.git",
		"post-install-cmd": "command -v vendor/bin/cghooks >/dev/null 2>&1 || exit 0; vendor/bin/cghooks add --git-dir=.git",
		"post-update-cmd": "command -v vendor/bin/cghooks >/dev/null 2>&1 || exit 0; vendor/bin/cghooks update --git-dir=.git",
		"phplint": "./vendor/bin/phplint",
		"test": [
			"@composer run phplint"
		]
	},
	"scripts-descriptions": {
		"test": "Run all tests"
	},
	"extra": {
		"hooks": {
			"pre-commit": [
				"composer run test"
			],
			"post-merge": "composer install"
		}
	}
}
```

**Comment by BrainMaestro** [comment] 2019-10-15 10:13
@devnix the idea for the `cghooks.lock` is that it represents the local state of your git hooks. Imagine that the file is committed and a new developer start working on the project. Their hooks will not be installed correctly. The fix for `.gitignore` can be done by appending a blank line as well.

The `--no-dev` feature was reverted, so, yes it does not work. The previous implementation did not work as expected. I have just updated the release note from `2.7.0` to make that clear. Also, you shouldn't need to specify `.git`, that's kind of strange. Could you create a reproducible repo so I can take a look? When you have time of course.

Thanks for the feedback!

**Comment by devnix** [comment] 2019-10-15 13:46
Hi @BrainMaestro!

I get the point of the lockfile, maybe I did not explain it correctly:

Let's imagine that I configure the `"post-install-cmd": "cghooks add --ignore-lock"` line, and I run `composer install`. `cghooks` will modify my `.gitignore` by adding a new line with the lockfile.

Now, my coworker does a `composer install` too. As he still does not have any lockfile, `cghooks` will modify my `.gitignore` again. This will occur each time someone configures a new workspace of the project.

That's why I'm suggesting to rethink the behavior or, at least, the recommendations on the readme file.

The example I provided on the first post solves this problem, and the `--no-dev` problem too.

I'm not worried about the `.git` problem because it's a strange environment, but if you are curious, it happened on a container based on this:

```dockerfile
FROM php:7.0.27-apache

RUN apt-get update && apt-get install git -y
```

I found that the `git rev-parse --git-common-dir` command gives an empty output inside that container (with my volume setted up)

**Comment by BrainMaestro** [comment] 2019-10-15 14:21
Oh right, now I understand. We should actually check the lockfile first before doing the modification. Would you be interested in doing a fix? It shouldn't be too tricky unless we do more sophisticated matching. The alternative which is not to have `--ignore-lock` would likely cause accidental commits and mess up the git hook generation for new users. I think I still want to keep the recommendation

For the docker issue, it's because the version of git installed in the container is quite old (`2.1.4` - released in 2014)  and does not understand the `--git-common-dir` output. This can be fixed.

**Comment by BrainMaestro** [comment] 2019-10-15 14:49
Actually, I just checked, and this lockfile behavior (checking if it already exists in the `.gitignore`) is already present and should work correctly after #98. I made a commit to fix the `--git-dir` problem. As for the last one (needing `command -v`), I'm not sure of how to handle it

**Comment by devnix** [comment] 2019-10-15 14:59
Yes, `cghooks` checks if exists a lockfile, and then adds the lockfile to the gitignore. The problem is that if another person checks out the project, `cghooks` will not detect any lockfile, and will add a repeated line to the gitignore. This will happen every time you execute `composer install` with the `--ignore-lock` configuration.

The solution would be to manually modify the gitignore, or parse the gitignore to avoid duplicating the line.

**Comment by devnix** [comment] 2019-10-15 15:00
By the way, adba29aff812d0903c8985cafe2780714de0da2b seems to work like a charm!

**Comment by devnix** [comment] 2019-10-15 15:05
Oh, okay, just found your strpos check, you were meaning that, right?

**Comment by BrainMaestro** [comment] 2019-10-15 15:18
Yes, looks like it's broken though

**Comment by devnix** [comment] 2019-10-15 16:13
`vendor/bin/cghooks add --ignore-lock` still reports `You did not specify a git directory to use`, using `dev-master f90b682`

**Comment by BrainMaestro** [comment] 2019-10-16 10:21
But I thought you said it worked before?

**Comment by devnix** [comment] 2019-10-16 10:58
> By the way, [adba29a](https://github.com/BrainMaestro/composer-git-hooks/commit/adba29aff812d0903c8985cafe2780714de0da2b) seems to work like a charm!

It seems like I accidentally ran my old composer script  with the `--git-dir` :man_facepalming:

**Comment by BrainMaestro** [comment] 2019-10-16 11:44
Can you run `git rev-parse --git-common-dir` and `git rev-parse --git-dir` and let me know what they return?

**Comment by devnix** [comment] 2019-10-16 13:58
```
www-data@b7b360a4808d:~/html$ git rev-parse --git-common-dir
--git-common-dir
www-data@b7b360a4808d:~/html$ git rev-parse --git-dir
.git
```

**Comment by BrainMaestro** [comment] 2019-10-16 14:15
Okay as expected. I found the bug in the function, so it should work now. 🤞

**Comment by devnix** [comment] 2019-10-17 07:19
It's working now. Thank you!

**Comment by BrainMaestro** [comment] 2019-10-17 08:01
Okay great, can you test the `--ignore-lock` behavior? If all is good, I'll make another patch release

**Comment by devnix** [comment] 2019-10-17 10:43
I tested it too, and I think it's working fine!

**Comment by BrainMaestro** [comment] 2019-10-17 11:12
Okay, great. if you have any ideas for avoiding the `command -v` pattern, let me know. I'll close this issue now and create a release. Thanks for the help

**Closed by BrainMaestro** 2019-10-17 11:12 UTC

**Comment by BrainMaestro** [comment] 2019-10-17 11:18
@devnix, you can use the new release https://github.com/BrainMaestro/composer-git-hooks/tree/v2.8.2 now

**Comment by aman00323** [comment] 2019-10-17 12:02
@devnix you can use `composer update nothing` this command will not update your packages untill you have changes in your `composer.json`

**Comment by devnix** [comment] 2019-10-17 12:05
> @devnix you can use `composer update nothing` this command will not update your packages untill you have changes in your `composer.json`

Yeah, but I guess the whole point is to integrate git hooks into your Composer workflow, and not to modify it :smile:

**Comment by BrainMaestro** [comment] 2019-10-17 12:54
@devnix I understand the idea behind the lockfile and maybe I can actually get rid of. I'll consider that for v3. However, I was specifically asking about the issue with needing `command -v`

**Comment by devnix** [comment] 2019-10-17 14:58
@BrainMaestro Not sure, I'm still not 100% aware of the internals of a Composer plugin, but I guess that if the hooks are managed by the package automatically with the behavior I've proposed, it should work as expected even when switching the `--no-dev` flag on and off.

**Comment by devnix** [comment] 2019-10-17 15:10
Hm, I guess we could move our conversation to chat or email to avoid flooding the issue!

**Comment by dylan-kerr** [comment] 2019-12-09 21:14
I ran into this same issue and wasn't 100% happy with the solution above as it is not portable across shells (both PowerShell and Bash, in my case). I solved it by adding a script that skips the following scripts in a non-dev install:

`src/Utility/ComposerScripts.php`
```php
<?php

namespace Utility;

use Composer\Script\Event;

class ComposerScripts
{
    /**
     * Run scripts that follow only if dev packages are installed.
     */
    public static function devModeOnly(Event $event)
    {
        if (!$event->isDevMode()) {
            $event->stopPropagation();
            print("Skipping {$event->getName()} as this is a non-dev installation.\n");
        }
    }
}
```

`composer.json` (excerpt)
```json
{
    "autoload": {
        "psr-4": {
            "Utility\\": "src/Utility"
        }
    },
    "scripts": {
        "post-install-cmd": [
            "Utility\\ComposerScripts::devModeOnly",
            "cghooks add --ignore-lock"
        ],
        "post-update-cmd": [
            "Utility\\ComposerScripts::devModeOnly",
            "cghooks update"
        ]
    }
}
```

**Comment by devnix** [comment] 2019-12-10 07:41
I'm looking forward to get some free time and try a new strategy purely based on a Composer plugin, without a CLI tool or a lockfile to maintain a list of hooks.

**Comment by BrainMaestro** [comment] 2019-12-10 09:15
@dylan-kerr that's not such a bad solution. @devnix a composer plugin sounds like the right strategy. Maybe that can be adapted to this as a possible `3.0`?

**Comment by simioluwatomi** [comment] 2020-02-04 10:32
Great plugin here. I installed it into a project at work because I want our workflow to be more standardized. However, I am experiencing problems after running a deployment to production. This is because production servers install composer dependencies with the `--no-dev` flag.

Because I had to do the deployment, my temporary fix was to remove the commands I had setup.

What is the permanent fix that you suggest for those who install this in an environment with the `no-dev` flag?

Thank you

**Comment by devnix** [comment] 2020-02-04 12:20
For me, my definitive solution was to hack my `composer.json`:
```json
"scripts": {
	"pre-install-cmd": "command -v vendor/bin/cghooks >/dev/null 2>&1 || exit 0; vendor/bin/cghooks remove",
	"post-install-cmd": "command -v vendor/bin/cghooks >/dev/null 2>&1 || exit 0; vendor/bin/cghooks add",
	"post-update-cmd": "command -v vendor/bin/cghooks >/dev/null 2>&1 || exit 0; vendor/bin/cghooks update",
},
```

I will leave it like that until a new version is published fixing this behavior, or until I get some spare time to write my own implementation (not in the short term).

**Comment by BrainMaestro** [comment] 2020-02-06 13:14
@simioluwatomi glad you like it. I would do as @devnix suggested or you can create a simple shell script that does the same (checks for whether `cghooks` is present and forwards the parameters if it is, and does nothing otherwise).

I haven't had the time to come up with a broader solution

**Comment by simioluwatomi** [comment] 2020-02-07 11:21
> @simioluwatomi glad you like it. I would do as @devnix suggested or you can create a simple shell script that does the same (checks for whether `cghooks` is present and forwards the parameters if it is, and does nothing otherwise).
> 
> I haven't had the time to come up with a broader solution

Thanks for the suggestion. but I'm no expert at bash scripting.




> For me, my definitive solution was to hack my `composer.json`:
> 
> ```json
> "scripts": {
> 	"pre-install-cmd": "command -v vendor/bin/cghooks >/dev/null 2>&1 || exit 0; vendor/bin/cghooks remove",
> 	"post-install-cmd": "command -v vendor/bin/cghooks >/dev/null 2>&1 || exit 0; vendor/bin/cghooks add",
> 	"post-update-cmd": "command -v vendor/bin/cghooks >/dev/null 2>&1 || exit 0; vendor/bin/cghooks update",
> },
> ```
> 
> I will leave it like that until a new version is published fixing this behavior, or until I get some spare time to write my own implementation (not in the short term).

Thanks!!! But I keep getting `The system cannot find the path specified.` for all the scripts.

Maybe it helps if I mention that I am running on windows and use git bash.

**Comment by devnix** [comment] 2020-02-07 12:03
Are you using Windows, @simioluwatomi?

**Comment by simioluwatomi** [comment] 2020-02-07 12:14
> Are you using Windows, @simioluwatomi?

Yep! I mentioned that earlier too

**Comment by devnix** [comment] 2020-02-07 12:35
Oh damn, sorry, didn't saw the last line. Maybe you could try MYSYS or an equivalent Windows command? I think this would be out of the scope of this repo

**Comment by simioluwatomi** [comment] 2020-02-07 15:26
I think I'll just install it as a normal dependency. I'll think of something later.

**Comment by dylan-kerr** [comment] 2020-02-07 17:43
Simi: the approach I suggested on this issue a couple of months ago uses a
custom ComposerScripts class is fully cross platform and tested on Windows,
so that might be worth trying.

**Comment by HeWhoWas** [comment] 2020-04-01 10:56
Here's my solution, though it's linux only:

```
"scripts": {
	"cghooks": "app/Vendor/bin/cghooks",
	"post-install-cmd": "test -f app/Vendor/bin/cghooks && app/Vendor/bin/cghooks add --ignore-lock || true",
	"post-update-cmd": "test -f app/Vendor/bin/cghooks && app/Vendor/bin/cghooks update || true"
}
```

**Comment by VanTigranyan** [comment] 2020-11-16 18:09
Hey @devnix I have the same problem on the prod env, as we are running the command with --no-dev. Any updates here so far? I found nothing in the docs.

**Comment by devnix** [comment] 2020-11-17 07:07
Hey @VanTigranyan, not really, no. I think for now this is the best solution:

> For me, my definitive solution was to hack my `composer.json`:
> 
> ```json
> "scripts": {
> 	"pre-install-cmd": "command -v vendor/bin/cghooks >/dev/null 2>&1 || exit 0; vendor/bin/cghooks remove",
> 	"post-install-cmd": "command -v vendor/bin/cghooks >/dev/null 2>&1 || exit 0; vendor/bin/cghooks add",
> 	"post-update-cmd": "command -v vendor/bin/cghooks >/dev/null 2>&1 || exit 0; vendor/bin/cghooks update",
> },
> ```
> 
> I will leave it like that until a new version is published fixing this behavior, or until I get some spare time to write my own implementation (not in the short term).

**Comment by leymannx** [comment] 2021-07-12 20:46
Problem might be that `remove` creates a lock file if running in that order. See https://github.com/BrainMaestro/composer-git-hooks/issues/119.

Seems you are safer having it more like @HeWhoWas has it, and maybe even prevent the lock file from being created at all:

```json
"scripts": {
	"post-install-cmd": "command -v vendor/bin/cghooks >/dev/null 2>&1 || exit 0; vendor/bin/cghooks add --no-lock",
	"post-update-cmd": "command -v vendor/bin/cghooks >/dev/null 2>&1 || exit 0; vendor/bin/cghooks update",
}
```
