### ISSUE TITLE
git commit not committing after completing pre-commit scripts

### ISSUE THREAD

**Issue by tylerrehm-id** [BrainMaestro/composer-git-hooks#86] opened 2019-06-13 15:15 UTC
This is probably a dumb question or something simple I am overlooking but for some reason no matter what I do I cannot seem to get my git commit -m"message here" to actually commit upon completion of the pre-commit hook. I have seen elsewhere online where if the hook returns 0 then the commit should complete as expected. I have even added multiple variations of exit 0 as the last script within the pre-commit array but with no luck.

- I have tried composer dump-autoload, composer cghooks update, etc.
- I have also installed cghooks both locally within the project and globally within composer.

The pre-commit hooks is running as expected but fails to actually add the new commit upon completion. 

Not sure if this helps but I am working on a Laravel 5.8 project using and using the virtual box vm 'laravel/homestead' version '7.1.0'.

I have spent more time than I'd like to admit trying to get this to work so any help would be greatly appreciated. I hope this is the right channel to post this. Thanks!

**When running git commit and then git status:**

vagrant@homestead:~/code/notiifii$ git commit -m"test"
committing as xxxxxxx@xxxxxxxxxxx.com
Loaded config default from ".php_cs".

Fixed all files in 13.107 seconds, 12.000 MB memory used

vagrant@homestead:~/code/notiifii$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   .gitignore
	new file:   .php_cs
	modified:   app/Console/Kernel.php
	modified:   composer.json
	modified:   composer.lock
	modified:   routes/web.php

**Here is the hooks section of my composer.json file. These are found under the extra section.**

`"hooks": {
            "pre-commit": [
                "echo committing as $(git config user.email)",
                "php-cs-fixer fix --config=.php_cs",
                "git add ."
            ],
            "pre-push": [
                "php-cs-fixer fix --dry-run --config=.php_cs",
                "phpunit"
            ],
            "post-merge": "composer install"
        },`

**Comment by BrainMaestro** [comment] 2019-06-13 15:37
Hi @tylerrehm-id, This is probably because the pre-commit is failing for some reason. Can you try simplifying the pre-commit hook to just the `echo` statement which can never actually fail, and then try again.

**Comment by tylerrehm-id** [comment] 2019-06-13 15:42
I completed the below but still behaving the same way 

- changed the pre-commit hook to below
- composer dump-autoload 
- composer cghooks update

**only output**
vagrant@homestead:~/code/notiifii$ git commit -m"test"
hello world

**new pre-commit hook config**
```
"pre-commit": [
                "echo hello world"
            ],
```

**Comment by BrainMaestro** [comment] 2019-06-13 15:51
if you remove the hook completely, does it work?

**Comment by tylerrehm-id** [comment] 2019-06-13 18:50
Removing the hook with cghooks does not work, looks like its not update the .git/hooks/pre-commit script.
I removed this package and the hooks directory from .git/hooks and everything looks back to normal. I tried removing from composer.json, cghook remove but no luck.

Not the end of the world, just don't understand what is going wrong. There are no errors reported and if I manually run the php-cs-fixer command and then git add . then git commit, works just fine.

**Comment by BrainMaestro** [comment] 2019-06-14 08:29
Hmm this is very strange. Can you try to set up a public repo from scratch and see if you can reproduce this? It would help a lot with investigating the issue.

**Comment by tylerrehm-id** [comment] 2019-06-14 14:40
Yes strange indeed.
I will have to do this weekend at some point. In the meantime, I just manually edited my git hooks for pre-commit and it is working as expected.

Thanks for the help on this one! Once I set up that repo, will link here for you.

**Comment by jaceju** [comment] 2019-06-18 09:30
I had the same issue, and it resolved after I removed `.git/hooks/commit-msg`.

**Comment by BrainMaestro** [comment] 2019-06-18 09:36
@jaceju maybe the hook was failing?

**Comment by jaceju** [comment] 2019-06-19 03:25
@BrainMaestro You are right. I ignored the commit message should match "ABC-123: Fix everything".

Thanks for your great work.

**Comment by BrainMaestro** [comment] 2019-06-19 09:13
@jaceju that's good to hear. @tylerrehm-id I'll close this now, but when you have more info, feel free to open another issue.

**Closed by BrainMaestro** 2019-06-19 09:13 UTC

**Comment by juliosouzam** [comment] 2020-09-21 14:24
> I had the same issue, and it resolved after I removed `.git/hooks/commit-msg`.

this work for me, thank you.

**Comment by hagios2** [comment] 2021-11-29 08:00
Thanks @jaceju, it worked for me too
